#!/usr/bin/env node
/**
 * ReplenishRadar MCP Server - stdio bridge to REST API.
 * Generated by scripts/sync-mcp-surfaces.mjs from packages/mcp-server/tools.manifest.json.
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

type ToolDefinition = {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties?: Record<string, unknown>;
    required?: string[];
  };
};

const API_KEY = process.env.REPLENISHRADAR_API_KEY;
const BASE_URL = process.env.REPLENISHRADAR_API_URL || 'https://api.replenishradar.com';

if (!API_KEY) {
  console.error('Missing required environment variable: REPLENISHRADAR_API_KEY');
  process.exit(1);
}

const TOOLS: ToolDefinition[] = [
  {
    "name": "rr_get_stockout_risk",
    "description": "Get items at risk of stocking out, sorted by days to stockout. Filter by risk level, SKU, or store.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "risk_level": {
          "type": "string",
          "description": "Filter by risk level (critical, high, medium, low)"
        },
        "sku": {
          "type": "string",
          "description": "Filter by SKU"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 100, max 500)"
        }
      }
    }
  },
  {
    "name": "rr_get_inventory_position",
    "description": "Get stock-by-location breakdown for a single item. Returns on-hand quantities across all warehouses and stores.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "item_id": {
          "type": "string",
          "description": "Item UUID"
        },
        "sku": {
          "type": "string",
          "description": "Canonical SKU (used if item_id not provided)"
        }
      }
    }
  },
  {
    "name": "rr_get_demand_forecast",
    "description": "Get demand forecast statistics (mu/sigma) for a SKU or item. Returns active forecast windows.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "sku": {
          "type": "string",
          "description": "Canonical SKU"
        },
        "item_id": {
          "type": "string",
          "description": "Item UUID"
        },
        "window_days": {
          "type": "integer",
          "description": "Filter by forecast window (e.g., 7, 14, 30)"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        }
      }
    }
  },
  {
    "name": "rr_get_suggested_purchase_orders",
    "description": "Get system-generated purchase order suggestions based on demand forecasts and stockout risk.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "description": "Filter by status (suggested, approved, dismissed)"
        },
        "vendor_id": {
          "type": "string",
          "description": "Filter by vendor/supplier ID"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 100, max 500)"
        }
      }
    }
  },
  {
    "name": "rr_get_replenishment_actions",
    "description": "List canonical buyer work across supplier PO, transfer, combined, and no-action replenishment outcomes. Prefer this over suggested purchase orders or alerts for deciding what action to take next.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "description": "Optional status filter, comma-separated"
        },
        "kind": {
          "type": "string",
          "description": "Optional kind filter: supplier_po, transfer, combined, no_action"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by parent store or child origin store"
        },
        "origin_location_id": {
          "type": "string",
          "description": "Filter by child origin location UUID"
        },
        "source_location_id": {
          "type": "string",
          "description": "Filter by parent source location UUID"
        },
        "destination_location_id": {
          "type": "string",
          "description": "Filter by parent or child destination location UUID"
        },
        "sku": {
          "type": "string",
          "description": "Filter by child SKU"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 100, max 500)"
        }
      }
    }
  },
  {
    "name": "rr_get_replenishment_action",
    "description": "Get one replenishment action with child item provenance, immutable snapshots, linked execution records, and event history.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "action_id": {
          "type": "string",
          "description": "Replenishment action UUID"
        }
      },
      "required": [
        "action_id"
      ]
    }
  },
  {
    "name": "rr_get_alerts",
    "description": "Get inventory alerts (stockout warnings, sync failures, reorder points). Supports filtering by type, severity, status, and SKU.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "description": "Filter by status (active, acknowledged, snoozed, resolved, all)"
        },
        "alert_type": {
          "type": "string",
          "description": "Filter by alert type"
        },
        "severity": {
          "type": "string",
          "description": "Filter by severity"
        },
        "sku": {
          "type": "string",
          "description": "Filter by SKU"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 50, max 500)"
        },
        "offset": {
          "type": "integer",
          "description": "Pagination offset"
        }
      }
    }
  },
  {
    "name": "rr_list_items",
    "description": "List catalog items with optional search, vendor filtering, and pagination. Returns SKU, display name, lead time, and supplier info.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "search": {
          "type": "string",
          "description": "Search by SKU or display name"
        },
        "vendor_id": {
          "type": "string",
          "description": "Filter by primary supplier ID"
        },
        "needs_review": {
          "type": "boolean",
          "description": "Filter items flagged for review"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 100, max 500)"
        },
        "offset": {
          "type": "integer",
          "description": "Pagination offset"
        }
      }
    }
  },
  {
    "name": "rr_get_sync_status",
    "description": "Get recent data sync runs (Shopify, Amazon). Returns sync status, timing, and error details.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "connector_type": {
          "type": "string",
          "description": "Filter by connector (shopify, amazon)"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 10, max 100)"
        }
      }
    }
  },
  {
    "name": "rr_list_suppliers",
    "description": "List all suppliers/vendors for the organization. Optionally include vendor SKU mappings.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "include_skus": {
          "type": "boolean",
          "description": "Include vendor SKU mappings (default false)"
        }
      }
    }
  },
  {
    "name": "rr_list_purchase_orders",
    "description": "List purchase orders with filtering by status, vendor, and search. Supports pagination.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "description": "Filter by status (comma-separated: draft,sent,approved,received,cancelled)"
        },
        "vendor_id": {
          "type": "string",
          "description": "Filter by vendor ID"
        },
        "search": {
          "type": "string",
          "description": "Search by PO number"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 50, max 200)"
        },
        "offset": {
          "type": "integer",
          "description": "Pagination offset"
        }
      }
    }
  },
  {
    "name": "rr_get_purchase_order",
    "description": "Get a single purchase order with full details including line items and vendor info.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_get_po_pdf",
    "description": "Get the PDF generation endpoint for a purchase order.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_get_po_documents",
    "description": "List documents attached to a purchase order (invoices, packing slips, etc.).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_get_po_notes",
    "description": "Get notes/comments on a purchase order.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_get_sales_history",
    "description": "Get daily sales history (units sold, revenue) for a SKU or store over a date range.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "sku": {
          "type": "string",
          "description": "Filter by SKU"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        },
        "days": {
          "type": "integer",
          "description": "Lookback period in days (default 30, max 90)"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 1000, max 5000)"
        }
      }
    }
  },
  {
    "name": "rr_get_top_sellers",
    "description": "Get top-selling SKUs ranked by units sold over a date range.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "days": {
          "type": "integer",
          "description": "Lookback period in days (default 30, max 90)"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 20, max 100)"
        }
      }
    }
  },
  {
    "name": "rr_get_slow_movers",
    "description": "Overstock / dead-stock / slow movers: SKUs you are holding (on-hand > 0) that aren't selling. Returns on_hand, units sold in the window, and a dead_stock flag. Inventory-first, so never-sold dead stock is surfaced too.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "days": {
          "type": "integer",
          "description": "Lookback period in days (default 30, max 90)"
        },
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 20, max 100)"
        }
      }
    }
  },
  {
    "name": "rr_get_inventory_value",
    "description": "Get total inventory value and per-SKU breakdown. Cost/value fields require sensitive_read capability.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "store_id": {
          "type": "string",
          "description": "Filter by store ID"
        }
      }
    }
  },
  {
    "name": "rr_get_sku_health",
    "description": "Get a high-level SKU health snapshot: stockout risk counts by level and active alert counts by type.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "rr_get_lost_sales",
    "description": "Estimate lost sales from current stockouts based on demand velocity and days out of stock.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "days": {
          "type": "integer",
          "description": "Analysis period in days (default 30, max 90)"
        }
      }
    }
  },
  {
    "name": "rr_get_store_health",
    "description": "Diagnose connected store health, sync status, and connection errors.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "rr_get_data_freshness",
    "description": "Get data freshness by inventory dimension before quoting operational numbers.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "rr_get_setup_status",
    "description": "Get onboarding milestones, setup completion state, and next recommended step.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "rr_get_recent_activity",
    "description": "Get recent alerts, purchase orders, and sync activity counts.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "days": {
          "type": "integer",
          "description": "Lookback period in days (default 7, max 30)"
        }
      }
    }
  },
  {
    "name": "search_knowledge",
    "description": "Search ReplenishRadar product knowledge for grounded answers.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Knowledge search query"
        },
        "top_k": {
          "type": "integer",
          "description": "Maximum number of results"
        },
        "limit": {
          "type": "integer",
          "description": "Alias for top_k"
        }
      },
      "required": [
        "query"
      ]
    }
  },
  {
    "name": "rr_evaluate_fit",
    "description": "Evaluate whether ReplenishRadar fits your use case (deterministic ICP + tier match) and capture demand signal. Mirrors the public agent-intake survey; reads no org data.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "channels": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "shopify",
              "amazon",
              "other"
            ]
          },
          "description": "Sales channels you sell on"
        },
        "sku_count_band": {
          "type": "string",
          "enum": [
            "under_50",
            "50_500",
            "500_2k",
            "2k_20k",
            "20k_50k",
            "over_50k"
          ],
          "description": "Approximate SKU count band"
        },
        "store_count": {
          "type": "integer",
          "description": "Number of stores"
        },
        "primary_pain": {
          "type": "string",
          "enum": [
            "stockouts",
            "overstock",
            "forecasting",
            "po_automation",
            "fba"
          ],
          "description": "Primary inventory pain"
        },
        "autonomy_intent": {
          "type": "string",
          "enum": [
            "read",
            "draft",
            "autonomous"
          ],
          "description": "How autonomously the agent will act"
        },
        "tier": {
          "type": "string",
          "enum": [
            "A",
            "B",
            "C"
          ],
          "description": "Intake tier reached"
        },
        "attribution_token": {
          "type": "string",
          "description": "Opaque token to thread a multi-step evaluation session"
        }
      }
    }
  },
  {
    "name": "rr_trigger_sync",
    "description": "Trigger a data sync from Shopify or Amazon. Respects 5-minute cooldown to prevent spam.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "connector_type": {
          "type": "string",
          "enum": [
            "shopify",
            "amazon"
          ],
          "description": "Platform to sync from"
        },
        "store_id": {
          "type": "string",
          "description": "Store ID (auto-resolved if omitted)"
        }
      },
      "required": [
        "connector_type"
      ]
    }
  },
  {
    "name": "rr_acknowledge_alert",
    "description": "Acknowledge an active alert with an optional note.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "alert_id": {
          "type": "string",
          "description": "Alert UUID"
        },
        "note": {
          "type": "string",
          "description": "Optional acknowledgement note"
        }
      },
      "required": [
        "alert_id"
      ]
    }
  },
  {
    "name": "rr_create_purchase_order",
    "description": "Create a new purchase order (always created as draft). Include line items with SKUs and quantities.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "vendor_id": {
          "type": "string",
          "description": "Supplier/vendor UUID"
        },
        "destination_location_id": {
          "type": "string",
          "description": "Exact receiving location UUID"
        },
        "action_id": {
          "type": "string",
          "description": "Optional replenishment action UUID to link this PO to"
        },
        "po_number": {
          "type": "string",
          "description": "Custom PO number (auto-generated if omitted)"
        },
        "notes": {
          "type": "string",
          "description": "PO notes"
        },
        "expected_delivery_date": {
          "type": "string",
          "description": "Expected delivery date (ISO 8601)"
        },
        "items": {
          "type": "array",
          "description": "Line items",
          "items": {
            "type": "object",
            "properties": {
              "sku": {
                "type": "string"
              },
              "quantity": {
                "type": "integer"
              },
              "unit_cost": {
                "type": "number"
              }
            }
          }
        }
      },
      "required": [
        "vendor_id",
        "destination_location_id"
      ]
    }
  },
  {
    "name": "rr_update_purchase_order",
    "description": "Update a draft or in-review purchase order (notes, expected delivery date, vendor).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        },
        "notes": {
          "type": "string",
          "description": "Updated notes"
        },
        "expected_delivery_date": {
          "type": "string",
          "description": "Updated expected delivery date"
        },
        "vendor_id": {
          "type": "string",
          "description": "Updated vendor ID"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_add_po_note",
    "description": "Add a note/comment to a purchase order.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        },
        "content": {
          "type": "string",
          "description": "Note content"
        }
      },
      "required": [
        "po_id",
        "content"
      ]
    }
  },
  {
    "name": "rr_request_approval",
    "description": "Request human approval for a purchase order. Returns a time-limited approval URL (15 min) to share with a team member.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        },
        "message": {
          "type": "string",
          "description": "Message for the approver"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_send_purchase_order",
    "description": "Mark an approved purchase order as sent. Requires prior human approval via rr_request_approval.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        },
        "action_id": {
          "type": "string",
          "description": "Optional replenishment action UUID to append a send event to"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_cancel_purchase_order",
    "description": "Cancel a purchase order. Cannot cancel POs with status cancelled, received, or closed.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_add_replenishment_action_note",
    "description": "Add a note to a replenishment action.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "action_id": {
          "type": "string",
          "description": "Replenishment action UUID"
        },
        "note": {
          "type": "string",
          "description": "Note content"
        }
      },
      "required": [
        "action_id",
        "note"
      ]
    }
  },
  {
    "name": "rr_dismiss_replenishment_action",
    "description": "Dismiss a replenishment action with an optional reason.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "action_id": {
          "type": "string",
          "description": "Replenishment action UUID"
        },
        "reason": {
          "type": "string",
          "description": "Dismissal reason"
        }
      },
      "required": [
        "action_id"
      ]
    }
  },
  {
    "name": "rr_prepare_replenishment_action",
    "description": "Preview a replenishment action and return its current updated_at before executing. Use the returned updated_at as expected_updated_at on execute/resolve/retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "action_id": {
          "type": "string",
          "description": "Replenishment action UUID"
        }
      },
      "required": [
        "action_id"
      ]
    }
  },
  {
    "name": "rr_execute_replenishment_action",
    "description": "Execute a replenishment action in draft mode: creates a draft purchase order and/or draft transfer order for the action's items. Idempotent by idempotency_key; rejects with conflict if the action changed since prepare (stale expected_updated_at) or if the same key is reused with a different payload or actor. Never auto-sends to suppliers and never commits stock.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "action_id": {
          "type": "string",
          "description": "Replenishment action UUID"
        },
        "idempotency_key": {
          "type": "string",
          "description": "Caller-chosen idempotency key; replay with the same key + payload returns the original result"
        },
        "expected_updated_at": {
          "type": "string",
          "description": "The action updated_at from rr_prepare_replenishment_action; execute fails if it no longer matches"
        }
      },
      "required": [
        "action_id",
        "idempotency_key",
        "expected_updated_at"
      ]
    }
  },
  {
    "name": "rr_resolve_replenishment_action",
    "description": "Resolve a replenishment action as no-action with a reason. Idempotent; requires idempotency_key and expected_updated_at and applies the same stale-state conflict contract as execute.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "action_id": {
          "type": "string",
          "description": "Replenishment action UUID"
        },
        "reason": {
          "type": "string",
          "description": "Reason the action needs no procurement/transfer"
        },
        "idempotency_key": {
          "type": "string",
          "description": "Caller-chosen idempotency key"
        },
        "expected_updated_at": {
          "type": "string",
          "description": "The action updated_at the resolution was decided against"
        }
      },
      "required": [
        "action_id",
        "reason",
        "idempotency_key",
        "expected_updated_at"
      ]
    }
  },
  {
    "name": "rr_retry_replenishment_action",
    "description": "Retry a blocked or failed replenishment action by re-running the draft execution path. Idempotent; requires idempotency_key and expected_updated_at and applies the same stale-state conflict contract as execute.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "action_id": {
          "type": "string",
          "description": "Replenishment action UUID"
        },
        "idempotency_key": {
          "type": "string",
          "description": "Caller-chosen idempotency key"
        },
        "expected_updated_at": {
          "type": "string",
          "description": "The action updated_at the retry was decided against"
        }
      },
      "required": [
        "action_id",
        "idempotency_key",
        "expected_updated_at"
      ]
    }
  },
  {
    "name": "rr_get_document_upload_url",
    "description": "Create a document record for a purchase order (invoice, packing slip, etc.). Requires Scale tier.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        },
        "filename": {
          "type": "string",
          "description": "Document filename"
        },
        "document_type": {
          "type": "string",
          "description": "Document type (default: attachment)"
        },
        "description": {
          "type": "string",
          "description": "Document description"
        }
      },
      "required": [
        "po_id",
        "filename"
      ]
    }
  },
  {
    "name": "rr_record_pi_review",
    "description": "Record proforma invoice details on a purchase order (PI number, date, total, terms).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "po_id": {
          "type": "string",
          "description": "Purchase order UUID"
        },
        "pi_number": {
          "type": "string",
          "description": "Proforma invoice number"
        },
        "pi_date": {
          "type": "string",
          "description": "PI date (ISO 8601)"
        },
        "pi_total": {
          "type": "number",
          "description": "PI total amount"
        },
        "pi_terms": {
          "type": "string",
          "description": "Payment terms"
        }
      },
      "required": [
        "po_id"
      ]
    }
  },
  {
    "name": "rr_create_location",
    "description": "Create a manual inventory location such as warehouse, 3PL, or inbound location.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Location name"
        },
        "type": {
          "type": "string",
          "enum": [
            "warehouse",
            "3pl",
            "fba",
            "wfs",
            "in_transit",
            "inbound"
          ],
          "description": "Location type"
        },
        "address_line1": {
          "type": "string",
          "description": "Street address"
        },
        "city": {
          "type": "string",
          "description": "City"
        },
        "state": {
          "type": "string",
          "description": "State or province"
        },
        "postal_code": {
          "type": "string",
          "description": "Postal code"
        },
        "country": {
          "type": "string",
          "description": "Country"
        },
        "is_default": {
          "type": "boolean",
          "description": "Whether this should be the default manual location"
        }
      },
      "required": [
        "name",
        "type"
      ]
    }
  },
  {
    "name": "rr_set_stock_at_location",
    "description": "Set stock quantity for a SKU at a manual location.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "location_id": {
          "type": "string",
          "description": "Manual location UUID"
        },
        "location_name": {
          "type": "string",
          "description": "Manual location name, used if location_id is omitted"
        },
        "sku": {
          "type": "string",
          "description": "Canonical SKU"
        },
        "quantity": {
          "type": "integer",
          "description": "New on-hand quantity"
        }
      },
      "required": [
        "sku",
        "quantity"
      ]
    }
  },
  {
    "name": "rr_get_agent_context",
    "description": "Get one agent context entry by namespace and key. Expired entries are omitted. The namespace must be granted to this API key by a human admin.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string",
          "description": "Allowlisted context namespace (for example supplier_rules)"
        },
        "key": {
          "type": "string",
          "description": "Entry key within the namespace (max 200 chars)"
        }
      },
      "required": [
        "namespace",
        "key"
      ]
    }
  },
  {
    "name": "rr_set_agent_context",
    "description": "Store a bounded JSON object under a namespace and key. The value must be a JSON object (max 16 KiB), must not contain secrets or raw PII, and ttl_seconds is optional and capped at 90 days. The namespace must be granted to this key.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string",
          "description": "Allowlisted context namespace"
        },
        "key": {
          "type": "string",
          "description": "Entry key within the namespace (max 200 chars)"
        },
        "value": {
          "type": "object",
          "description": "JSON object value (max 16 KiB, no secrets or PII)"
        },
        "scope_ref": {
          "type": "string",
          "description": "Optional descriptive scope label (max 200 chars, non-secret)"
        },
        "ttl_seconds": {
          "type": "integer",
          "description": "Optional expiry in seconds (max 7776000 = 90 days)"
        }
      },
      "required": [
        "namespace",
        "key",
        "value"
      ]
    }
  },
  {
    "name": "rr_list_agent_context",
    "description": "List live agent context entries for a single namespace. The namespace is required and the limit is bounded (max 200). This tool never lists across namespaces.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string",
          "description": "Allowlisted context namespace (required)"
        },
        "limit": {
          "type": "integer",
          "description": "Max results (default 50, max 200)"
        },
        "key_prefix": {
          "type": "string",
          "description": "Optional key prefix filter"
        }
      },
      "required": [
        "namespace"
      ]
    }
  },
  {
    "name": "rr_delete_agent_context",
    "description": "Delete one agent context entry by namespace and key. Records actor provenance. The namespace must be granted to this key.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string",
          "description": "Allowlisted context namespace"
        },
        "key": {
          "type": "string",
          "description": "Entry key within the namespace"
        }
      },
      "required": [
        "namespace",
        "key"
      ]
    }
  }
];

async function callApi(toolName: string, input: Record<string, unknown>): Promise<unknown> {
  const resp = await fetch(
    `${BASE_URL}/api/mcp/call`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`,
      },
      body: JSON.stringify({ tool: toolName, input }),
    },
  );

  if (!resp.ok) {
    const errorBody = await resp.text();
    throw new Error(`API error ${resp.status}: ${errorBody}`);
  }

  const data = await resp.json() as { result: unknown };
  return data.result;
}

async function main() {
  const server = new Server(
    { name: 'replenishradar', version: '1.0.6' },
    { capabilities: { tools: {} } },
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: TOOLS,
  }));

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const { name, arguments: args } = request.params;
    try {
      const result = await callApi(name, (args as Record<string, unknown>) || {});
      return {
        content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return {
        content: [{ type: 'text', text: `Error: ${message}` }],
        isError: true,
      };
    }
  });

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((error) => {
  console.error('MCP server fatal error:', error);
  process.exit(1);
});
